package itouchtv.commons;

/**
 * Created by zhouliangchou on 2016/8/11.
 */
public interface ErrorConstants {

    int ERROR_CODE_ACCOUNT_NOT_EXIST = 40006;
    int ERROR_CODE_ACCOUNT_OR_PASSWORD_MISMATCH = 40007;
    int ERROR_CODE_NEW_PASSWORD_SAME_AS_OLD_PASSWORD = 40010;
    int ERROR_CODE_LOGIN_FAILURE_EXCEEDS_THRESHOLD = 40015;
    int ERROR_CODE_DUPLICATE_ROLENAME = 40016;
    int ERROR_CODE_DUPLICATE_ACOUNT = 40017;
    int ERROR_CODE_ACCOUNT_NOT_STATUS = 40018;
    int ERROR_CODE_MEDIA_LIVE_NOT_EXIST = 42001;
    int ERROR_CODE_COMPLAINTCATEGORY_INVALID = 42004;
    int ERROR_CODE_STREAM_HANDLE_ERROR = 42003;
    int ERROR_CODE_MGRSYSTEMSETTING_INVALID = 42005;
    int ERROR_CODE_ENTITY_NOT_EXIST = 42006;
    int ERROR_CODE_STREAM_STATUS = 42007;
    int ERROR_CODE_TAG_NOT_EXIST = 42009;
    int ERROR_CODE_JWT_INVALIDATE = 42008;
    int ERROR_CODE_ALBUM_CHANGE = 42011;
    int ERROR_CODE_ALBUM_NOT_EXIST = 420012;
    int ERROR_CODE_ALBUMNEWS_IS_EXIST = 420013;
    int ERROR_CODE_INVALID_PUSH_MSG = 420019;
    int ERROR_CODE_INVALID_PUSH_CONTENT_TYPE = 420015;
    int ERROR_CODE_INVALID_PUSH_TYPE = 420016;
    int ERROR_CODE_INVALID_PUSH_MSG_STATUS = 420018;
    int ERROR_CODE_INVALID_PUSH_DATE = 420020;
    int ERROR_CODE_NEWS_IS_TOP_EXIST_ONE = 420014;
    int ERROR_CODE_REPUSH_FAILED = 420021;
    int ERROR_CODE_PUSHTYPE_NOTSUPPORTED = 420022;
    int ERROR_CODE_PUSHSTATUS_NOTSUPPORTED = 420023;
    int ERROR_CODE_INVALID_COMMENT_WONDERFUL = 420024;
    int ERROR_CODE_INVALID_COMMENT_STATUS = 420025;

    int ERROR_CODE_CHANNEL_IS_EXSIT_NAME = 420027;
    int ERROR_CODE_TAG_IS_EXSIT_NAME = 420028;
    int ERROR_CODE_INVALID_FORMAT_GENERIC = 49001;
    int ERROR_CODE_JPUSH_MEDIALIVE_BEFOR_lIVEBEGINTIME = 49002;
    int ERROR_CODE_API_ACCESS_DENIED = 49003;
    int ERROR_CODE_TIMESTAMP_INVALID = 40001;
    int ERROR_CODE_NEWS_RELEASESTATUS_INVALID = 40002;
    int ERROR_CODE_PUSH_MSG_FORBIDDEN = 40003;
    int ERROR_CODE_MEDIA_STATUS_INVALID = 40004;
    int ERROR_CODE_INVALID_NEWS_STATUS = 40005;
    int ERROR_CODE_MEDIA_LIVE_OPSTATUS_CHANGE = 40006;
    int ERROR_CODE_MEDIA_LIVE_STREAM_NOT_EXIST = 40007;
    int ERROR_CODE_INVALID_SHARE_DATA_TYPE = 40008;

    int ERROR_CODE_INVALID_MEDIALIVE_CHATSTATUS = 49004;
    int ERROR_CODE_INVALID_MEDIA_HOME_SHOW = 49005;
    int ERROR_CODE_ACTIVITY_EXISTED = 49006;
    int ERROR_CODE_SPIDER_TAG_PARAMETER_ILLEGAL = 49007;

    String ERROR_MSG_JWT_INVALIDATE = "帐号登录状态已失效，请重新登录！";
    String ERROR_MSG_DUPLICATE_ACOUNT = "账号  %s 已存在，请重新输入！";
    String ERROR_MSG_ACCOUNT_NOT_EXIST = "账号不存在，请重新输入！";
    String ERROR_MSG_ACCOUNT_OR_PASSWORD_MISMATCH = "账号或者密码不匹配，请重新输入！";
    String ERROR_MSG_NEW_PASSWORD_SAME_AS_OLD_PASSWORD = "密码不正确，请重新输入！";
    String ERROR_MSG_ACCOUNT_NOT_STATUS = "账号 %s 已被封停，请联系管理员解封！";
    String ERROR_MSG_DUPLICATE_ROLENAME = "角色名称   %s  已存在，请重新输入！";
    String ERROR_MSG_MEDIA_LIVE_NOT_EXIST = "该节目信息不存在";
    String ERROR_MSG_STREAM_HANDLE_ERROR = "流处理异常，请再尝试一次！";
    String ERROR_MSG_LOGIN_FAILURE_EXCEEDS_THRESHOLD = "连续5次密码错误，账号锁定1小时！";
    String ERROR_MSG_COMPLAINTCATEGORY_INVALID = " ID: %s 的意见不存在！";
    String ERROR_MSG_MGRSYSTEMSETTING_INVALID = "ID: %s 的参数不存在！";
    String ERROR_MSG_ENTITY_NOT_EXIST = " %s 条件异常";
    String ERROR_MSG_STREAM_STATUS = "直播状态异常！";
    String ERROR_MSG_TAG_NOT_EXIST = "标签不存在或已被删除！";
    String ERROR_MSG_ALBUM_CHANGE = "状态已发生改变，请重新尝试！";
    String ERROR_MSG_ALBUM_NOT_EXIST = "该专辑不存在或已被删除！";
    String ERROR_MSG_ALBUMNEWS_IS_EXIST = "第  %s 个视频已在其它专辑存在！";
    ;
    String ERROR_MSG_INVALID_PUSH_MSG = "该推送消息不存在！";
    String ERROR_MSG_INVALID_PUSH_CONTENT_TYPE = "推送内容类型不正确";
    String ERROR_MSG_INVALID_PUSH_TYPE = "推动类型不正确";
    String ERROR_MSG_INVALID_PUSH_MSG_STATUS = "推送消息状态不正确";
    String ERROR_MSG_NEWS_IS_TOP_EXIST_ONE = "只能置顶一篇文章，如需要置顶请先取消原置顶文章！";
    String ERROR_MSG_INVALID_PUSH_DATE = "推送时间不正确";
    String ERROR_MSG_REPUSH_FAILED = "重新推送失败";
    String ERROR_MSG_PUSHTYPE_NOTSUPPORTED = "推送类型不支持";
    String ERROR_MSG_PUSHSTATUS_NOTSUPPORTED = "推送状态为已推送，不可重复推送";
    String ERROR_MSG_INVALID_COMMENT_WONDERFUL = "是否精彩评论不正确";
    String ERROR_MSG_INVALID_COMMENT_STATUS = "是否允许评论不正确";
    String ERROR_MSG_CHANNEL_IS_EXSIT_NAME = "该 %s 频道已存在！ ";
    String ERROR_MSG_JPUSH_MEDIALIVE_BEFOR_lIVEBEGINTIME = "推送时间不得早于直播开始时间";
    String ERROR_MSG_TIMESTAMP_INVALID = "时间验证失败，不能小于当前时间!";
    String ERROR_MSG_NEWS_RELEASESTATUS_INVALID = "新闻的状态设置不正确";
    String ERROR_MSG_PUSH_MSG_FORBIDDEN = "该消息被禁止推送";
    String ERROR_MSG_MEDIA_STATUS_INVALID = "节目状态不正确";
    String ERROR_MSG_INVALID_NEWS_STATUS = "新闻状态不正确";
    String ERROR_MSG_MEDIA_LIVE_OPSTATUS_CHANGE = "节目状态已经出现变化";
    String ERROR_MSG_MEDIA_LIVE_STREAM_NOT_EXIST = "节目流不存在";
    String ERROR_MSG_TAG_IS_EXSIT_NAME = "该标签名已存在！ ";
    String ERROR_MSG_API_ACCESS_DENIED = "拒绝访问";
    String ERROR_MSG_INVALID_MEDIALIVE_CHATSTATUS = "直播弹幕状态不正确";
    String ERROR_MSG_INVALID_SHARE_DATA_TYPE = "请求数据类型错误";
    String ERROR_MSG_INVALID_MEDIA_HOME_SHOW = "节目的状态已发生改变";
    String ERROR_MSG_ACTIVITY_EXISTED = "首页悬浮活动已存在";
    String ERROR_MSG_PARAMETER_ILLEGAL = "参数 %s 不正确";

}
