spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 150
  jpa:
    database: MYSQL
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  redis:
    pool:
      max-active: 1000
      max-idle: 100
      max-wait: 10000
      min-idle: 0
    timeout: 3000

eureka:
  client:
    preferSameZoneEureka: true
  instance:
    preferIpAddress: true

server:
  port: 8180
  undertow:
    worker-threads: 150

logging:
  file: ./log/user-service.log
